### PR TITLE
More control for Identity Holders

### PR DESCRIPTION
**Pull request by ArthurManz**

### CODE REVIEW

**Review by ChristopherA — APPROVED** [review]

**Comment by ChristopherA** [comment]
Only needs a link added to the README.md

**Comment by ArthurManz** [comment]
Great! 😄 Thank you very much! I will do it right away.

**Comment by ArthurManz** [comment]
Done 👍

**Comment by ChristopherA** [comment]
Can you fix the merge conflict on the README.md?

**Comment by ArthurManz** [comment]
Done, thank you. 😃

**Comment by ChristopherA** [comment]
Still unable to merge

**Comment by ArthurManz** [comment]
Fixed

**Pull request merged**
